name: Testing CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ap-south-1

    - name: Download PEM file from S3
      run: |
        aws s3 cp s3://${{ secrets.PEM_OBJECT_KEY }} ./secret.key
        chmod 600 ./secret.key

    - name: Run Command on Server
      run: |
        ssh -i "secret.key" -o StrictHostKeyChecking=yes ubuntu@ec2-65-0-21-186.ap-south-1.compute.amazonaws.com "cd / && make restart_web"
