name: Testing CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1 
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
  
    - name: Download PEM file from S3
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        PEM_OBJECT_KEY: ${{ secrets.TEST_PEM_OBJECT_KEY }}
        CONFIG_OBJECT_KEY: ${{ secrets.TEST_CONFIG_OBJECT_KEY }}
      run: |
        aws s3 cp s3://$S3_BUCKET/$PEM_OBJECT_KEY ./secret.key
        chmod 600 ./secret.key
        mkdir $GITHUB_WORKSPACE/deploy/env
        aws s3 cp s3://$S3_BUCKET/$CONFIG_OBJECT_KEY ./deploy/env/config.yaml
    - name: Run Command on Server
      run: |
        ssh -i "secret.key" -o StrictHostKeyChecking=no ubuntu@ec2-65-0-21-186.ap-south-1.compute.amazonaws.com "cd / && make restart_web"
